blank_issues_enabled: true
contact_links:
  - name: Discord
    about: You can join our Discord support server.
    url: https://l.devwtf.in/plura-dc
  - name: Twitter
    about: You can follow us on Twitter.
    url: https://x.com/getplura